name: Jacoco

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./aluguel
  
jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/**/aluguel/target/test-results/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min_coverage_overall: 1
          min-coverage-changed-files: 1

      - name: Fail PR if overall coverage is less than 1%
        if: ${{ steps.jacoco.outputs.coverage-overall < 1.0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Overall coverage is less than 1%!')
